# Generated by Django 3.0.4 on 2020-09-06 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='description . . . '),
            preserve_default=False,
        ),
    ]
